services:
  mongo:
    image: mongo:6
    container_name: mongo-scraper
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: privacy_monitor
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
